### ISSUE TITLE
Logs will not be displayed

### ISSUE THREAD

**Issue by scott4dev** [coopnorge/provider-github#72]
I'm trying `package: xpkg.upbound.io/coopnorge/provider-github:v0.10.0` and in the console of the `provider-github-****` I have this info message

```
{"level":"info","ts":"2024-04-19T11:30:45Z","logger":"provider-github","msg":"Beta feature enabled","flag":"EnableBetaManagementPolicies"}
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 648 [running]:
	>  runtime/debug.Stack()
	>  	runtime/debug/stack.go:24 +0x5e
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	sigs.k8s.io/controller-runtime@v0.17.0/pkg/log/log.go:60 +0xcd
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithValues(0xc00054fb00, {0xc000ca2540, 0x2, 0x2})
	>  	sigs.k8s.io/controller-runtime@v0.17.0/pkg/log/deleg.go:168 +0x49
	>  github.com/go-logr/logr.Logger.WithValues(...)
	>  	github.com/go-logr/logr@v1.4.1/logr.go:332
	>  sigs.k8s.io/controller-runtime/pkg/builder.(*Builder).doController.func1(0xc000ca2520)
	>  	sigs.k8s.io/controller-runtime@v0.17.0/pkg/builder/controller.go:400 +0x173
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000678aa0, {0x22f4c80, 0xc000548be0}, {0x1d3d060?, 0xc000ca2500?})
	>  	sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:306 +0x16a
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000678aa0, {0x22f4c80, 0xc000548be0})
	>  	sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266 +0x1af
	>  sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	>  	sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227 +0x79
	>  created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 98
	>  	sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:223 +0x565
```

**Comment by lacroi-m-insta** [comment]
Have you tried running the application with the --debug flag ?

If you are running in kubernetes your DeploymentRuntimeConfig would look like this:
```
spec:
  deploymentTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - -d
```
